

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FNAME VARCHAR(24), 
  LNAME VARCHAR(24), 
  ADDRESS VARCHAR(64),
  STATE VARCHAR(12),
  DOB DATE, 
  SSN VARCHAR(12), 
  PHONENUM VARCHAR(24)
);


CREATE TABLE CANDIDATE(
  CANDIDATE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FNAME VARCHAR(24), 
  LNAME VARCHAR(24), 
  PARTY VARCHAR(24), 
  OFFICE VARCHAR(32)
);

CREATE TABLE BALLOT(
  BALLOT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  CANDIDATE_ID BIGINT NOT NULL,
  OFFICE VARCHAR(32) NOT NULL
);


CREATE TABLE SURVEY(
  QUESTION VARCHAR(100), 
  ANSWER VARCHAR(45),
  TOPIC VARCHAR(35)
);

CREATE TABLE ISSUE(
ISSUE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  OPINION VARCHAR(45),
  TOPIC VARCHAR(35)
  );
